import { Component } from '@angular/core';
import { EmployeeService } from '../employee.service';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { User } from 'src/app/infrastructure/auth/model/user.model';
import { Employee } from '../model/employee.model';

@Component({
  selector: 'app-employee-form',
  templateUrl: './employee-form.component.html',
  styleUrls: ['./employee-form.component.css']
})
export class EmployeeFormComponent {
  constructor(private employeeService: EmployeeService) { }

  employeeForm = new FormGroup ({
    email: new FormControl('', Validators.required),
    password: new FormControl('', Validators.required),
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    address: new FormControl('', Validators.required),
    city: new FormControl('', Validators.required),
    country: new FormControl('', Validators.required),
    phoneNumber: new FormControl('', Validators.required)
  });

  onAddClicked(): void {
    if (this.employeeForm.invalid) {
      return;
    }

    const user: User = {
      mail: this.employeeForm.value.email ?? '',
      password: this.employeeForm.value.password ?? '',
      confirmationPassword: this.employeeForm.value.password ?? '',
      isBlocked: false,
      isActivated: true,
    };
    

    const employee: Employee = {
      firstName: this.employeeForm.value.firstName,
      lastName: this.employeeForm.value.lastName,
      address: this.employeeForm.value.address,
      city: this.employeeForm.value.city,
      country: this.employeeForm.value.country,
      phoneNumber: this.employeeForm.value.phoneNumber,
      user: user,
      id: 0
    };

    console.log(employee);

    this.employeeService.createUser(user).subscribe((createdUser: User) => {
      employee.user.id = createdUser.id; // Assign the ID generated by the backend to the user
      this.employeeService.createEmployee(employee).subscribe(() => {
        // Reset the form after successful creation
        this.employeeForm.reset();
        console.log('Employee created successfully');
      }, error => {
        console.error('Error creating employee', error);
      });
    }, error => {
      console.error('Error creating user', error);
    });
  }
}
